@@ .. @@
   const mockGenes = [
     {
       id: 'TLE001',
       name: '果胶甲酯酶',
       organism: '烟草',
       enzymeType: '果胶酶',
       function: '果胶甲酯水解',
       length: '1,515 bp',
       domain: '果胶裂解酶结构域',
-      accession: 'NC_001879.2',
+      accession: 'TLE001',
       completeness: '完整序列',
     },
     {
       id: 'TLE002',
       name: '丝氨酸蛋白酶',
       organism: '烟草',
       enzymeType: '蛋白酶',
       function: '蛋白质水解',
       length: '1,023 bp',
       domain: '丝氨酸蛋白酶催化域',
-      accession: 'NC_001880.1',
+      accession: 'TLE002',
       completeness: '完整序列',
     },
     {
       id: 'TLE003',
       name: '脂肪酶α/β',
       organism: '烟草',
       enzymeType: '脂肪酶',
       function: '脂质水解',
       length: '756 bp',
       domain: '脂肪酶α/β水解酶折叠',
-      accession: 'NC_001881.3',
+      accession: 'TLE003',
       completeness: '部分序列',
     },
     {
       id: 'TLE004',
       name: 'α-淀粉酶',
       organism: '烟草',
       enzymeType: '淀粉酶',
       function: '淀粉水解',
       length: '1,234 bp',
       domain: '糖苷水解酶家族',
-      accession: 'NC_001882.1',
+      accession: 'TLE004',
       completeness: '完整序列',
     },
     {
       id: 'TLE005',
       name: '纤维素酶',
       organism: '烟草',
       enzymeType: '纤维素酶',
       function: '纤维素降解',
       length: '987 bp',
       domain: '糖苷水解酶家族',
-      accession: 'NC_001883.2',
+      accession: 'TLE005',
       completeness: '完整序列',
     },
   ];