-- 添加更多测试数据
INSERT INTO genes (name, organism, enzyme_type, function, sequence, length, domain, accession, completeness) VALUES
-- 果胶酶类
('果胶裂解酶2', '林烟草', '果胶酶', '果胶裂解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 1245, '果胶裂解酶结构域', 'TLE013', 'complete'),
('果胶酯酶3', '绒毛烟草', '果胶酶', '果胶酯水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 987, '果胶裂解酶结构域', 'TLE014', 'complete'),

-- 蛋白酶类
('丝氨酸蛋白酶2', '林烟草', '蛋白酶', '蛋白质水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 876, '丝氨酸蛋白酶催化域', 'TLE015', 'complete'),
('金属蛋白酶1', '绒毛烟草', '蛋白酶', '蛋白质降解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 1023, '金属蛋白酶结构域', 'TLE016', 'complete'),

-- 脂肪酶类
('磷脂酶C', '林烟草', '脂肪酶', '磷脂水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 765, '磷脂酶C结构域', 'TLE017', 'complete'),
('甘油脂酶1', '绒毛烟草', '脂肪酶', '甘油脂水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 897, '脂肪酶α/β水解酶折叠', 'TLE018', 'complete'),

-- 淀粉酶类
('葡聚糖酶1', '林烟草', '淀粉酶', '葡聚糖水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 1234, '糖苷水解酶家族', 'TLE019', 'complete'),
('α-葡萄糖苷酶', '绒毛烟草', '淀粉酶', '淀粉末端水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 876, '糖苷水解酶家族', 'TLE020', 'partial'),

-- 纤维素酶类
('纤维素酶1', '林烟草', '纤维素酶', '纤维素水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 1123, '糖苷水解酶家族', 'TLE021', 'complete'),
('β-葡萄糖苷酶', '绒毛烟草', '纤维素酶', '纤维素末端水解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 987, '糖苷水解酶家族', 'TLE022', 'complete'),

-- 木质素酶类
('漆酶1', '林烟草', '木质素酶', '木质素氧化', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 1456, '漆酶结构域', 'TLE023', 'complete'),
('木质素过氧化物酶2', '绒毛烟草', '木质素酶', '木质素降解', 'ATGGCTAGCAAGATCGACCTGAAGTACCTGGGCAAGTTCGAGCTGAACATCGACAAGCTGAAGGGCATCGACCTGAAGTTCGAGCTGAACATCGACAA', 1234, '木质素过氧化物酶', 'TLE024', 'complete');

-- 更新序列长度字段
UPDATE genes SET length = LENGTH(sequence) WHERE length = 0; 